export const SET_LATEST_PATCH_NOTE = 'SET_LATEST_PATCH_NOTE';
export const SET_PATCH_NOTES_STATE = 'SET_PATCH_NOTES_STATE';
export const ADD_PATCH_NOTE = 'ADD_PATCH_NOTE';
export const EDIT_PATCH_NOTE = 'EDIT_PATCH_NOTE';
