export const SET_STREAMERS = 'SET_STREAMERS';
export const SET_LOADING_STREAMERS = 'SET_LOADING_STREAMERS';
export const SET_STREAMERS_COMPARISONS = 'SET_STREAMERS_COMPARISONS';
export const SET_LOADING_COMPARISONS = 'SET_LOADING_COMPARISONS';
export const ON_GET_PARTICIPATIONS = 'ON_GET_STREAMERS_CHART_PARTICIPATIONS';
